
name: ci-workflow #name of the workflow


env: # at level of workflow
  PYTHON_VERSION: "3.12"
  DOCKER_IMAGE: "task-img-github-action"
  ECR_REGISTRY: "767196576807.dkr.ecr.eu-north-1.amazonaws.com"
  

on:

  workflow_dispatch: 

  push:
    paths:
      - "app/**"
      - "Dockerfile"
      - ".github/workflows/ci.yml"
    branches:
      - development # if i push directly to development will run the ci pipeline

  pull_request:
    types:
      - opened # if i open the PR will run the pipeline
      - reopened # if i reopen the PR will run the pipeline
      - synchronize # if i push some commits on Open PR will run the ci pipeline 
    branches:
      - dev # if i make PR from feature branch to dev 
      - main # if i make PR from dev to main



jobs:
  ci-job:
  
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v6
       

      - name : trivy fs scan 
        uses: aquasecurity/trivy-action@master # this action like  install trivy for you on vm and you can start use it , he actuall make container have trivy run inside of it and remove it after run
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"

      - name : trivy  scan docker file 
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "Dockerfile"
          format: "table"
      

      - name : install python to install ruff 
        uses: actions/setup-python@v6
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      
      - name: validate python version
        run: python --version

      - name: install ruff 
        run : pip install ruff

      - name: check ruff 
        run: ruff --version

      - name: do lint with ruff 
        run : ruff check .

      - name: build docker file 
        run : docker build -t ${DOCKER_IMAGE} .
      

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          scan-ref: "${{ env.DOCKER_IMAGE }}"
          format: "table"



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1


      - name: Login to Amazon ECR itself  # this like login to docker hub
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2



      - name: retag the image tob be compatible with ecr
        run: |
          docker tag ${DOCKER_IMAGE}:latest \
            ${ECR_REGISTRY}/${DOCKER_IMAGE}:latest

      - name: push to our repo on ecr 
        run : docker push  ${ECR_REGISTRY}/${DOCKER_IMAGE}:latest
